[build]
  command = "npm run build"
  publish = "dist"

[dev]
  command = "npm run dev"
  port = 8080

[[redirects]]
  from = "/auth/callback"
  to = "/auth/callback"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 